# Generated by Django 2.1.4 on 2018-12-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='upload_date',
        ),
    ]
