# Generated by Django 2.1.5 on 2019-01-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190106_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
    ]
