# Generated by Django 2.1.5 on 2019-01-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0005_auto_20190106_1635'),
        ('feedback', '0004_auto_20190107_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='book_name',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rater.Book'),
            preserve_default=False,
        ),
    ]
