# Generated by Django 2.1.4 on 2018-12-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_hash', models.CharField(max_length=100, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('ground_truth_label', models.IntegerField(blank=True)),
                ('predicted_label', models.IntegerField(blank=True)),
            ],
        ),
    ]
