# Generated by Django 2.1.5 on 2019-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_auto_20181229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ground_truth_label',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='predicted_label',
            field=models.CharField(max_length=1),
        ),
    ]
