# Generated by Django 2.1.5 on 2019-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_auto_20190106_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ground_truth_label',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='predicted_label',
            field=models.IntegerField(),
        ),
    ]
